config:
    # IDs & paths
    data_id: "exp_generator_v2"
    model_id: "finetuner_generator_low"
    models_dir: "../trained_models/exp_generator_v2"

    # Training params
    source: "generator_low"
    network_type: "low"
    iterations: 400
    num_classes: 30
    sigmoid_params: [500,150]
    batch_size: 500
    lr: 0.001

    # WANDB params
    enable_logging: True
    wandb_project_id: "finetuner_v2"

    # Network params
    num_hidden_layers: 3
    num_neurons: 60

    # Misc
    device: "cuda"