config:
    # IDs & paths
    data_id: "exp_generator_v2/classifier"
    model_id: "classifier"
    models_dir: "../trained_models/exp_generator_v2/"

    # Training params
    iterations: 30
    num_classes: 30
    sigmoid_params: [5000,1000]
    batch_size: 500
    lr: 0.0001

    # WANDB params
    enable_logging: True
    wandb_project_id: "classifier_v2"

    # Network params
    num_hidden_layers: 2
    num_neurons: 300

    # Misc
    device: "cpu"